# Generated by Django 5.0.6 on 2024-06-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockout_page', '0002_forcesid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mini_lockout',
            old_name='palyer2',
            new_name='player2',
        ),
    ]
