# Generated by Django 5.0.6 on 2024-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockout_page', '0003_rename_palyer2_mini_lockout_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mini_lockout',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
